$astart=2;
$aend=100;
$bstart=2;
$bend=100;

for($a=$astart;$a<=$aend;$a++) {
  for($b=$bstart;$b<=$bend;$b++) {
    $terms{$a**$b}++;
  }
}

print "There are ".scalar(keys %terms)." distinct terms are in the sequence generated by a^b for $astart <= a <= $aend and $bstart <= b <= $bend\n";
<>;